### ISSUE TITLE
Error when submitting in browsing

### ISSUE THREAD

**Issue by ProfessorShroom** [rimonhanna/Spotify-To-Youtube#23]
This is the error I get -
Error 500: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

**Comment by ProfessorShroom** [comment]
Now getting this error -
Error 500: Extra data: line 8 column 2 (char 326)

This is what comes up in the terminal -
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [21/Apr/2024 17:31:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2024 17:31:45] "GET /favicon.ico HTTP/1.1" 404 -
An exception occurred: Extra data: line 8 column 2 (char 326)
Traceback (most recent call last):
  File "/mnt/porygonData/Spotify-To-Youtube-main/web.py", line 36, in migrate
    data = json.load(ytmusic_headers_file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 8 column 2 (char 326)
127.0.0.1 - - [21/Apr/2024 17:32:06] "POST /migrate HTTP/1.1" 500 -
